FROM docker.io/api7/api7-ee-3-integrated:v3.9.5

COPY services/dashboard/conf.template.yaml /opt/api7-template/conf.template.yaml
COPY --chmod=755 services/dashboard/entrypoint.sh /opt/api7-template/entrypoint.sh

EXPOSE 7080 7443

ENTRYPOINT ["/opt/api7-template/entrypoint.sh"]
