FROM docker.io/api7/api7-ee-dp-manager:v3.9.5

COPY services/dp-manager/conf.template.yaml /opt/api7-template/conf.template.yaml
COPY --chmod=755 services/dp-manager/entrypoint.sh /opt/api7-template/entrypoint.sh

EXPOSE 7900 7943

ENTRYPOINT ["/opt/api7-template/entrypoint.sh"]
